title: My activity logs
description: My Personal Website
author: Chen Liana Lin
github: https://github.ibm.com/Liana-Lin
about: I'm a Research Staff Member at IBM T.J.Watson Research Center. I earned my Ph.D in Computer Science from North Carolina State University in 2017 under Dr.Min Chi.
disqus_shortname: lianahub
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/liana.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/chen-liana-lin-66541480/"
    - icon: fa-github
      link: "https://github.ibm.com/Liana-Lin"
    - icon: fa-google_scholar
      link: "https://scholar.google.com/citations?user=zkWwUIMAAAAJ&hl=en"

share:
  twitter_username:  
  fb_appid:

urls:
    - text: About Me
      url: /about/
    - text: Publication
      url: /publications/

url: "https://liana-lin.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
